# Generated by Django 2.1.3 on 2018-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('uid', models.CharField(default='defaultuid', max_length=200, unique=True)),
                ('company_type', models.CharField(choices=[('Bank', 'Bank'), ('HealthCare', 'HealthCare'), ('Education', 'Education'), ('RetailStores', 'RetailStores'), ('Others', 'Others')], max_length=10)),
                ('primary_color', models.CharField(max_length=10)),
                ('secondary_color', models.CharField(max_length=10)),
            ],
        ),
    ]
