# Generated by Django 2.1.3 on 2018-11-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAPI', '0002_auto_20181119_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Shopper', 'Shopper'), ('Buyer', 'Buyer'), ('Company_Admin', 'Company_Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('company_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200, null=True)),
                ('company_type', models.CharField(choices=[('Bank', 'Bank'), ('HealthCare', 'HealthCare'), ('Education', 'Education'), ('RetailStores', 'RetailStores'), ('Others', 'Others')], max_length=10)),
                ('primary_color', models.CharField(max_length=10, null=True)),
                ('secondary_color', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='UserAPI.User'),
        ),
    ]
