# Generated by Django 2.1.3 on 2018-11-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('accessory_type', models.CharField(choices=[('Adapters', 'Adapters'), ('Bags', 'Bags'), ('Mouse', 'Mouse'), ('Keyboards', 'Keyboards'), ('Headphones', 'Headphones')], max_length=10)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('Adapters', 'Laptops'), ('Desktops', 'Desktops'), ('Workstations', 'Workstations'), ('Servers', 'Servers'), ('Processors', 'Processors'), ('GPU', 'GPU'), ('Accessories', 'Accessories')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('inches', models.FloatField()),
                ('screen_resolution', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('Memory', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('price_euros', models.FloatField()),
                ('photo_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
