# Generated by Django 2.1.3 on 2018-11-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsAPI', '0002_auto_20181118_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.DeleteModel(
            name='Workstations',
        ),
        migrations.AddField(
            model_name='laptops',
            name='photo_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('Adapters', 'Laptops'), ('Desktops', 'Desktops'), ('Workstations', 'Workstations'), ('Servers', 'Servers'), ('Processors', 'Processors'), ('GPU', 'GPU'), ('Accessories', 'Accessories')], max_length=10),
        ),
    ]
