# Generated by Django 2.1.3 on 2018-11-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsAPI', '0003_auto_20181118_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('accessory_type', models.CharField(choices=[('Adapters', 'Adapters'), ('Bags', 'Bags'), ('Mouse', 'Mouse'), ('Keyboards', 'Keyboards'), ('Headphones', 'Headphones')], max_length=10)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
