# Generated by Django 2.1.3 on 2018-11-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsAPI', '0004_accessories_gpu_servers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desktops',
        ),
    ]
