# Generated by Django 2.1.3 on 2018-11-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsAPI', '0005_delete_desktops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
